### ISSUE TITLE
[Bug] i got to many poachers in my world

### ISSUE THREAD

**Issue by shonabudi** [0SoggyMustache0/ZAWA#132]
i got to many poachers in my world and they dont stop spawning

**Comment by JoelZBub** [comment]
Research beforehand? Are you on crack? This bug is because you installed a broken mod that literally hijacks vanilla spawn code. 
**I'm the person that discovered why this happens, and which mod is in conflict.** 
I've spent more time troubleshooting issues on this mod than most people have played it.
Your "solution" is not even a band-aid fix. It's a joke. 
Stop being a booger eater and do the one thing that will fix this problem... **Remove Custom Mob Spawner.**
